TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TomaszDrzewieckiCybercom2017.Controllers
{
    public class HomeController : Controller
    {

        
     Models.DBLibrary db = new Models.DBLibrary();
        // GET: Home
        public ActionResult Index()
        {
              //         db.TestDate();
            return View();
        }
       

        public ActionResult About()
        {
            ViewBag.Message = "Twoja Biblioteka";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Skontaktuj się ze mną.";
        
            return View();
        }
    }
}

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Controllers/ListaAutorowController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TomaszDrzewieckiCybercom2017.Models;

namespace TomaszDrzewieckiCybercom2017.Controllers
{
    public class ListaAutorowController : Controller
    {
        private DBLibrary db = new DBLibrary();

        // GET: ListaAutorow
        public ActionResult Index()
        {
            return View(db.tabAuthors.ToList());
        }

        // GET: ListaAutorow/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.tabAuthors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: ListaAutorow/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ListaAutorow/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Surname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.tabAuthors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: ListaAutorow/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.tabAuthors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: ListaAutorow/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: ListaAutorow/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.tabAuthors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: ListaAutorow/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.tabAuthors.Find(id);
            db.tabAuthors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Controllers/ListaKsiazekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TomaszDrzewieckiCybercom2017.Models;

namespace TomaszDrzewieckiCybercom2017.Controllers
{
    public class ListaKsiazekController : Controller
    {
        private DBLibrary db = new DBLibrary();

        // GET: ListaKsiazek
        public ActionResult Index()
        {
           // db.tabAuthors.Find(Author.id)


            return View(db.tabBooks.ToList());
        }

        // GET: ListaKsiazek/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.tabBooks.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: ListaKsiazek/Create
        public ActionResult Create()
        {

            ViewBag.Autorzy = (from item in db.tabAuthors
                                orderby item.Surname
                                select new SelectListItem { Value = item.Id.ToString(), Text = item.Surname }).ToList();
            return View();
        }

        // POST: ListaKsiazek/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AuthorId,Title,ISBN,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.tabBooks.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: ListaKsiazek/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.tabBooks.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: ListaKsiazek/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AuthorId,Title,ISBN,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: ListaKsiazek/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.tabBooks.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: ListaKsiazek/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.tabBooks.Find(id);
            db.tabBooks.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Controllers/ListaMieszanaController.cs
using System.Dynamic;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using System.Net;
using TomaszDrzewieckiCybercom2017.Models;

namespace TomaszDrzewieckiCybercom2017.Controllers
{
    public class ListaMieszanaController : Controller
    {

        private DBLibrary db = new DBLibrary();
        public ActionResult Index()
        {
            dynamic model = new ExpandoObject();
            model.Book = GetBooks();
            model.Author = GetAuthors();           
            return View(model);
        }
       
        private static List<Author> GetAuthors()
        {            
            DBLibrary db = new Models.DBLibrary();          
            var  authors = (from item in db.tabAuthors
                         orderby item.Name
                         select item).ToList();
            return authors;
        }
        // GET: ListaAutorow/Edit/5?rodzaj=
        public ActionResult Edit(int? id, string rodzaj )
        {            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (rodzaj != null)
            { 
                if (rodzaj == "ksiazka")
                {
                   Book book = db.tabBooks.Find(id);
                    if (book == null)
                    {
                        return HttpNotFound();
                    }
                    return View("EditBook", book);
                }
                else
                {                                  
                    Author author = db.tabAuthors.Find(id);
                    if (author == null)
                    {
                        return HttpNotFound();
                    }
                    return View("EditAuthor",author);
                }
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
        }
        // POST: ListaAutorow/Edit/5?rodzaj=
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "Id,Name,Surname")] Author author, [Bind(Include = "Id,Title,ISBN,ReleaseDate,AuthorId")] Book book, string rodzaj)
        {            
                if (rodzaj == "ksiazka")
                {
                    db.Entry(book).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else
                { 
                    db.Entry(author).State = EntityState.Modified;
                    db.SaveChanges();
                }             
            
            return RedirectToAction("Index");
        }

        private static List<Book> GetBooks()
        { 
            List<Book> books = new List<Book>();
            string query = "SELECT  Id, Title, AuthorId, ReleaseDate, ISBN  FROM Books";
            string constr = ConfigurationManager.ConnectionStrings["DBLibrary"].ConnectionString;

            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            books.Add(new Book
                            {
                                Id = Convert.ToInt32( sdr["Id"].ToString()),
                                Title = sdr["Title"].ToString(),
                              // ISBN = Convert.ToInt32(sdr["ISBN"].ToString()),
                              // ReleaseDate = Convert.ToInt32(sdr["ReleaseDate"].ToString()),
                            });
                        }
                    }
                    con.Close();
                    return books;
                }
            }
        }
    }
}

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Views/Home/About.cshtml
@{
    ViewBag.Title = "Dokumentacja Projektu";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


<h3>Rozdział 1. Utworzenie projektu "Biblioteka".</h3>
<div class="warning">
   Projekt utworzono na podstawie szablonu: "Aplikacja sieci Web platformy ASP.NET(.NET Framework wisual c#)" w programie Microsoft Visual Studio 2017.
</div>

<h3>Rozdział 2. Tworzymy Model Danych.</h3>
<p>
    Sprawdzamy connection string, czyli łańcuch połaczenia z bazą danych. W głównym katalogu aplikacji otwieramy plik Web.config.
    Odszukujemy fragment:
</p>
<code>
    <xmp><connectionStrings><add name="DBLibrary" connectionString="Data Source= itd." ... /></connectionStrings></xmp>
</code>
<p>Zwróć uwagę na to aby w zanczniku <add> element "name" wskazywał nazwę taką samą jak nazwa klasy, która dziedziczy po DBContext. W naszym przypadku, to DBLibrary, którą zaraz utworzymy.</p>

<p>W katalogu Models tworzymy klasy, z których powstanie model danych. Tabele, to zbiory obiektów danej klasy.</p>

<p>Kliknij prawym przyciskiem myszy na katalog "Models" Wybierz "Dodaj"-&gt;"Klasa.."</p>

<p>W oknie wpisujemy nazwę nowej klasy "Book.cs" i zatwierdzamy.</p>

<p>W utworzonym pliku wpisujemy:</p>

<code id="pierwszy">
    using System;<br />
    using System.Collections.Generic;<br/>
    using System.Linq;<br />
    using System.Web;<br />

    namespace NazwaProjektu.Models<br />
    {<br/>
    public class Book<br />
    {<br/>
    public int Id { get; set; }<br />
    public int AuthorId { get; set; }<br />
    public string Title { get; set; }<br />
    public int ISBN { get; set; }<br />   
    public int ReleaseDate { get; set; }<br />
    }</br>
    }<br />
</code>
<p>
    W miejscu "NazwaProjektu" wpisujemy nazwę swojego projektu.

    Analogicznie tworzymy jeszcze dwie kolejne klasy:
    Najpierw klasę "Author.cs".
</p>

<code>
    using System;<br />
    using System.Collections.Generic;<br />
    using System.Linq;<br />
    using System.Web;<br />

    namespace NazwaProjektu.Models<br />
    {<br />
    public class Author<br />
    {<br />
    public int Id { get; set; }<br />
    public string Name { get; set; }<br />
    public string Surname { get; set; }<br />
    }<br />
    }<br />
</code>
<p>oraz klasę "DBLibrary.cs"</p>

<code>
    using System.Web;<br />
    using System.Data.Entity;<br />
    namespace NazwaProjektu.Models<br />
    {<br />
    public class DBLibrary : DbContext<br />
    {<br />
    public DbSet tabBooks { get; set; }<br />
    public DbSet tabAuthors { get; set; }<br />
    public void TestDate()<br />
    {<br />
    Book s1 = new Models.Book() { Title = "Pan Tadeusz", ReleaseDate = 1834,  ISBN= 1, AuthorId = 1};<br />
    this.tabBooks.Add(s1);<br />
    this.tabBooks.Add(new Models.Book() { Title = "Grażyna", ReleaseDate = 1823, ISBN = 2, AuthorId = 1 });<br />
    this.tabBooks.Add(new Models.Book() { Title = "Dziady Część III", ReleaseDate = 1832, ISBN = 3, AuthorId = 1});<br />
    this.tabBooks.Add(new Models.Book() { Title = "Ballady i Romanse", ReleaseDate = 1822, ISBN = 4, AuthorId = 1});<br />
    this.tabBooks.Add(new Models.Book() { Title = "Ogniem i Mieczem", ReleaseDate = 1884, ISBN = 5, AuthorId = 2});<br />
    this.tabBooks.Add(new Models.Book() { Title = "Kordian", ReleaseDate = 1834, ISBN = 6, AuthorId = 3 });<br />
    this.tabBooks.Add(new Models.Book() { Title = "Balladyna", ReleaseDate = 1839, ISBN = 7, AuthorId = 3 });<br />
    this.tabAuthors.Add(new Models.Author(){Name = "Adam", Surname = "Mickiewicz" });<br />
    this.tabAuthors.Add(new Models.Author() { Name = "Juliusz", Surname = "Słowacki" });<br />
    this.SaveChanges();<br />
    }<br />
    }<br />
    }<br />
</code>

<p>Pamiętaj o podaniu odpowiedniej przestrzeni nazw w miejscu "NazwaProjektu" - takiej samej jak nazwa Twojego projektu.</p>

<p>Zwróć uwagę na metodę TestDate() klasy DBLibrary. Uruchamiamy ją tylko raz w celu utworzenia i wypełnienia bazy danych.</p>
<p>Jak to zrobić? </p>
<p>W kontrolerze HomeController dodajemy kilka wpisów:</p>
<code>
    using System;<br />
    using System.Collections.Generic;<br />
    using System.Linq;<br />
    using System.Web;<br />
    using System.Web.Mvc;<br />

    namespace NazwaProjektu.Controllers<br />
    {<br />
    public class HomeController : Controller<br />
    {<br />
    Models.DBLibrary db = new Models.DBLibrary();<br />
    public ActionResult Index()<br />
    {<br />
</code>
<p>tutaj uruchamiamy metodę tworząca bazę danych. Po pojedynczym uruchomieniu, możemy ją zakomentować -->//db.TestDate();</p>
<code>
    db.TestDate();<br />
    return View();<br />
    }<br />

    
    }<br />
    }<br />
</code>
<p>
    Teraz uruchamiamy projekt klikając w zieloną strzałkę na górnym menu. W wyniku otrzymamy wypełnioną bazę danych.
    Zatrzymujemy projekt. Bazę danych możemy zobaczyć klikając "widok"->"Eksplorator Serwera"->"Połączenia Danych" i nazwa naszej bazy. Kliknij Prawym przyciskiem na jedną z tabel i wybierz "Pokaż dane tabeli".

    Teraz możesz zakomentować wspomniany fragment w HomeController (//db.TestDate()).
</p>
<h3>Rozdział 3. Kontrolery i Akcje</h3>
<h3>Rozdział 4. Routing</h3>
<h3>Rozdział 5. SEO</h3>
etc.

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Autor projektu";
}
<h2>@ViewBag.Title.</h2>
<main role="main" class="container">

    <div class="row">

        <div class="col-sm-8 blog-main">

            <div class="blog-post">
                <h2 class="blog-post-title">Kim jest?</h2>
                <p class="blog-post-meta">Ur. w 1982r. w Bydgoszczy, żonaty, wykształcenie wyższe magisterskie.</p>
                
               
                <p>Zajmowałem się wieloma rzeczami <b> aby zdobyć doświadczenie</b>. 
                Praca w wyuczonym zawodzie diagnosty laboratoryjnego nie była dla mnie.
                Miszkałem <b>rok w Szwecji</b> pracując w fabryce Volvo C70. 
                    <b>Programowałem zdalnie</b> jako php webdeveloper przez pół roku.
                Zaplanowałem kamienie milowe mojego życia i idąc po wyznaczonej drodze skutecznie je przekraczam.
                    <b>Prowadziłem firmę</b> budowlaną-brukarską. </p>
                <p> Zbudowałem dom (wyremontowałem mieszaknie w ponad 100-letnim młynie), wziąłem ślub i nadszedł <b>czas na realizację</b> swej dawnej <b>pasji</b>.</p>               
                <h3>Mój pierwszy komputer.</h3>
                <p>Rodzice kupili mi ATARI 800XE i do dziś pamiętam niebieski ekran z napisem:</p>
                <pre class="atari"><code>READY<br />_
                    </code></pre>
                <p>Wtedy też miałem okazję poznać "abc" języka basic, które zaczerpnąłem z popularnego wówczas czasopisma "Bajtek". 
                </p>
                <h3>Dopiero w szkole średniej na nowo odkryłem programowanie.</h3>
                <p>Tworzyłem pierwsze strony html w MS FrontPage.</p>
               <p>Napisałem kilka serwisów internetowych, na których nauczyłem się programować.</p>
                <ul>
                    <li>Portal z ogłoszeniami drobnymi w PHP z jQuery.</li>
                    <li>Portal wypożyczalni narzędzi z CMS w CakePhp2 +Bootstrap.</li>
                    <li>kilka stron www na potrzeby własne i dla znajomych.</li>
                </ul>
                <p>Pracując jako zdalny programista poznałem podstawy c# i MS VisualStudio</p>                
                <p>Nie uważam się za nowicjusza w kwestii programowania, w kontekście tworzenia stron i niedużych sewrisów www.
                Mam świadomość  ogromu technologii i zakresu wiedzy jaką musi posiadać dzisiejszy programista.
                Zdecydowanie chcę się uczyć rzeczy praktycznych, potrzebnych w pracy zawodowej. 
                </p>
            </div><!-- /.blog-post -->         
        </div><!-- /.blog-main -->
        <aside class="col-sm-3 ml-sm-auto blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">                
                <h4>Trzy najważniejsze cechy jakie posiadam:</h4>
                <p>Umiejętność pracy w zespole, chęć rozwoju i zaangażowanie.</p>
                <img class="img-responsive" src="~/Content/img/tomekFoto.jpg" />
            </div>               
        </aside><!-- /.blog-sidebar -->
    </div><!-- /.row -->
</main><h3>@ViewBag.Message</h3>
<address>
    Tomasz Drzewiecki<br/>
    Mochle 65<br />
    86-014 Sicienko<br/>
    Polska<br />
    <abbr title="Phone">tel.:</abbr>
    +48 608-612-553
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:contact@tomaszdrzewiecki.pl">contact@tomaszdrzewiecki.pl</a><br />
   
</address>

TomaszDrzewieckiCybercom2017/TomaszDrzewieckiCybercom2017/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div>
    <h1>Biblioteka</h1>
    <p class="lead">Aplikacja ASP.NET MVC na potrzeby rekrutacji w firmie Cybercom Poland oddział w Bydgoszczy</p>
    
</div>

<div class="row">
    <div class="col-md-4 alert-danger">
        <h2>Autorzy</h2>
        <p>Zakładka wyświetla listę autorów oraz umożliwia operacje związane z ich edycją, dodawaniem i usuwaniem.</p>
        <p><input type="button" value="Więcej" class="btn btn-danger" onclick="location.href='@Url.Action( "Index", "ListaAutorow")'" /></p>
    </div>
    <div class="col-md-4 alert-info">
        <h2>Książki</h2>        
        <p>Zakładka wyświetla listę książek oraz umożliwia operacje związane z ich edycją, dodawaniem i usuwaniem.</p>
        <p><input type="button" value="Więcej" class="btn btn-info" onclick="location.href='@Url.Action( "Index", "ListaKsiazek")'" /></p>
    </div>
    <div class="col-md-4 alert-success">
        <h2>Lista autorów i książek</h2>
        <p>Wyświetla współną listę z możliwością edycji rekordów.</p>
        <p><input type="button" value="Więcej" class="btn btn-success" onclick="location.href='@Url.Action( "Index", "ListaMieszana")'" /></p>
    </div>
</div>